In [82]:
text = "žodis 😊"
print (text)

žodis 😊


In [83]:
prekes = ['a', 'b', 'c']
print (prekes.pop())
print (prekes)

c
['a', 'b']


# Namu darbai 4

3. Parašykite funkciją, kuri priims string tipo kintamąjį, gražinkite kiek tame stringę yra raidžių, skaičių ir skyrybos (specialių) ženklų, tarpų.

In [84]:
def symbol_extract(text: str):
    numbers = 0
    letters = 0
    spaces = 0
    specials = 0
    for symbol in text:
        if symbol.isalpha():
            letters += 1
        elif symbol.isdigit():
            numbers += 1
        elif symbol.isspace():
            spaces += 1
        else:
            specials +=1
    print (f'letters: {letters}, numbers: {numbers}, spaces: {spaces}, specials: {specials}')

symbol_extract("hello 148   !$%^#@^😊😊😊")

letters: 5, numbers: 3, spaces: 4, specials: 10


4. Parašykite funkciją, kuri priima tris skaičius, jie reikš nuo, iki ir žingsnis. Funkcija turi grąžinti listą skaičių tokių, kokius padavėte funkcijai.

In [85]:
def my_range(start, end, step=1):
    return list( range(start, end, step) )

print (my_range(4, 30) )
print (my_range(4, 30, 5) )

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[4, 9, 14, 19, 24, 29]


5.  Parašyti funkciją, kuri priima vieną list tipo kintamąjį, funkcija grąžina skirtumą tarp didžiausio skaičiaus ir mažiausio skaičiaus.

In [86]:
def list_minmax_diff(my_list):
    return max(my_list) - min(my_list)

print( list_minmax_diff( [1,4,10,36,-5] ) )

41


# Numpy

In [87]:
# galite irasyti is Jupyter aplinkos vietoje komandines eilutes
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## 2D array

In [88]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [89]:
print(a_list)
print(a_list[1])
print(a_list[1][1])

print([ row[0] for row in a_list])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[5, 6, 7, 8]
6
[1, 5, 9]


In [90]:
import numpy as np

In [91]:
np_array = np.array( a_list )
print(np_array)
print(type(np_array) )
print(np_array[1])
print(np_array[1][1])
print(np_array[1, 1], '\n') # [row index, column index]

print( np_array[ :, 0 ] )
print( np_array[ :, 2 ], '\n' )

print( np_array[ :2, 0 ], '\n' )

print( np_array[ :2, 1:3 ], '\n' )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
[5 6 7 8]
6
6 

[1 5 9]
[ 3  7 11] 

[1 5] 

[[2 3]
 [6 7]] 



In [92]:
print( np_array.shape )
print( len(np_array) )

(3, 4)
3


In [93]:
print( np_array[ :2, 1:3 ].shape )

(2, 2)


## 1D array

In [94]:
array_1d = np.array( [1,5,7,9,71,14] )

print( array_1d.shape )
print( len(array_1d) )
print( array_1d )

(6,)
6
[ 1  5  7  9 71 14]


In [95]:
list_1d = [1,5,7,9,71,14]
print ( list_1d * 3 )
print ( [ number * 3 for number in list_1d ] )
print ('numpy array')
print ( array_1d * 3 )
print ( array_1d / 3 )
print ( array_1d + 3 )
print ( array_1d % 2 )
print ( array_1d ** 5 )

[1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14]
[3, 15, 21, 27, 213, 42]
numpy array
[  3  15  21  27 213  42]
[ 0.33333333  1.66666667  2.33333333  3.         23.66666667  4.66666667]
[ 4  8 10 12 74 17]
[1 1 1 1 1 0]
[         1       3125      16807      59049 1804229351     537824]


In [96]:
print (array_1d)
list_1d = [1,5,7,9,71,14]
print (list_1d)
list_1d[2:4] = [10,25]
print (list_1d)
# list_1d[2:4] = 50 # error
# print (list_1d)
print ('numpy array')
array_1d[2:4] = [10,25]
print (array_1d)
array_1d[2:4] = 55
print (array_1d)

[ 1  5  7  9 71 14]
[1, 5, 7, 9, 71, 14]
[1, 5, 10, 25, 71, 14]
numpy array
[ 1  5 10 25 71 14]
[ 1  5 55 55 71 14]


## 3D array

In [97]:
arr_3d = np.array([
        [ 
            [1, 2, 3], 
            [4, 5, 6]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)
print (arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [98]:
print (arr_3d.shape )

(2, 2, 3)


In [99]:
arr_3d[:, :, 2] = 10 # 1st dim, 2nd dim, 3rd dim
# print(arr_3d)
arr_3d[1, 1, :2] = 55
print(arr_3d)

[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [55 55 10]]]


## Numpy speed

In [100]:
size = 1_000_000

In [101]:
# %%timeit # Jupyter komanda

py_list = list(range(size))

In [102]:
# %%timeit

np_arr = np.arange(size)

In [103]:
%%timeit
py_list_2 = [ number * 2 for number in py_list ]

KeyboardInterrupt: 

In [ ]:
%%timeit
np_rez = np_arr * 2

1.29 ms ± 13.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Numpy reshape

In [ ]:
np_array = np.arange(0,100,2)
print(np_array)
print(np_array.shape)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [ ]:
print( np_array.reshape( (5,10) ), '\n' )


[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]] 



In [ ]:
print( np_array.reshape( (2, 25) ) )

[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
  48]
 [50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
  98]]


In [ ]:
print( np_array.reshape( (5, 2, 5) ) )

[[[ 0  2  4  6  8]
  [10 12 14 16 18]]

 [[20 22 24 26 28]
  [30 32 34 36 38]]

 [[40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]]

 [[80 82 84 86 88]
  [90 92 94 96 98]]]


In [ ]:
print( np_array.reshape( (5, 5, 5) ) )

ValueError: cannot reshape array of size 50 into shape (5,5,5)

In [ ]:
print (np_array.reshape( (2,1,-1) ) ) # -1 - palieka tiek kiek telpa

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


## Numpy methods

In [104]:
array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [2,2], [4,3], [7,4] ],
    [ [3,2], [4,3], [7,4] ],
    [ [4,2], [4,3], [7,4] ],
]
)
print (array_3d.shape)

(4, 3, 2)


In [105]:
print (array_3d)

[[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]


In [106]:
np.mean( array_3d )

3.75

In [107]:
print ( 'matrix mean\n', np.mean( array_3d, axis=0 ) )

array([[2.5, 2. ],
       [4. , 3. ],
       [7. , 4. ]])

In [117]:
print ( 'Column mean\n', print (np.mean( array_3d, axis=1 ) ) )
# print (np.mean( array_3d, axis=1 ).shape)


[[4.         3.        ]
 [4.33333333 3.        ]
 [4.66666667 3.        ]
 [5.         3.        ]]
(4, 2)


In [119]:
print ( 'Row mean\n', np.mean( array_3d, axis=2 ) ) # row

Row mean
 [[1.5 3.5 5.5]
 [2.  3.5 5.5]
 [2.5 3.5 5.5]
 [3.  3.5 5.5]]


In [111]:
np_array = np.arange(0,20).reshape( (5,4) )
print (np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [120]:
print('Column mean',  np.mean( np_array, axis=0 ) )
print('Row mean', np.mean( np_array, axis=1 ) )

Column mean [ 8.  9. 10. 11.]
Row mean [ 1.5  5.5  9.5 13.5 17.5]


In [121]:
print (np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [122]:
np.std( np_array )

5.766281297335398

In [123]:
print('Column std',  np.std( np_array, axis=0 ) )
print('Row std', np.std( np_array, axis=1 ) )

Column std [5.65685425 5.65685425 5.65685425 5.65685425]
Row std [1.11803399 1.11803399 1.11803399 1.11803399 1.11803399]


In [124]:
print('Column sum',  np.sum( np_array, axis=0 ) )
print('Row sum', np.sum( np_array, axis=1 ) )

Column sum [40 45 50 55]
Row sum [ 6 22 38 54 70]


In [126]:
print (np_array.shape)
print( np_array.T )
print (np_array.T.shape)

(5, 4)
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
(4, 5)


## Numpy comparison

In [131]:
rand_array = np.random.randint(7,50, 100)
print( rand_array )

[49 16 14 33 38 29 21 30 30 20  7 19 20 44 31 47 46 15 49 45 40 18 46 36
 43 11 18 12 27 27 10 43 27 10 25 23 14 11 15 45 29 18 46 35 28 19 10 19
 34 46 45 42 46 42 22 32 16 26 33 21 39 38  9 42 36 46 31 19 28 13 43 41
 18 24 46 29 41 35  9 28 32  8 38 42 33  9 16 36 10 47 27 28 47 13 24 49
 27 42 31 40]


In [132]:
rand_array[ rand_array > 18 ]

array([49, 33, 38, 29, 21, 30, 30, 20, 19, 20, 44, 31, 47, 46, 49, 45, 40,
       46, 36, 43, 27, 27, 43, 27, 25, 23, 45, 29, 46, 35, 28, 19, 19, 34,
       46, 45, 42, 46, 42, 22, 32, 26, 33, 21, 39, 38, 42, 36, 46, 31, 19,
       28, 43, 41, 24, 46, 29, 41, 35, 28, 32, 38, 42, 33, 36, 47, 27, 28,
       47, 24, 49, 27, 42, 31, 40])

In [133]:
rand_array[ rand_array > 30 ]

array([49, 33, 38, 44, 31, 47, 46, 49, 45, 40, 46, 36, 43, 43, 45, 46, 35,
       34, 46, 45, 42, 46, 42, 32, 33, 39, 38, 42, 36, 46, 31, 43, 41, 46,
       41, 35, 32, 38, 42, 33, 36, 47, 47, 49, 42, 31, 40])

In [134]:
rand_array > 30 # this is called a mask

array([ True, False, False,  True,  True, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False,  True,  True, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False,  True, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True, False, False, False,  True,  True,
       False, False,  True, False,  True,  True, False, False,  True,
       False,  True,  True,  True, False, False,  True, False,  True,
       False, False,  True, False, False,  True, False,  True,  True,
        True])

In [135]:
rand_array[ rand_array % 3 == 0 ]

array([33, 21, 30, 30, 15, 45, 18, 36, 18, 12, 27, 27, 27, 15, 45, 18, 45,
       42, 42, 33, 21, 39,  9, 42, 36, 18, 24,  9, 42, 33,  9, 36, 27, 24,
       27, 42])

In [139]:
print (rand_array)

[49 16 14 33 38 29 21 30 30 20  7 19 20 44 31 47 46 15 49 45 40 18 46 36
 43 11 18 12 27 27 10 43 27 10 25 23 14 11 15 45 29 18 46 35 28 19 10 19
 34 46 45 42 46 42 22 32 16 26 33 21 39 38  9 42 36 46 31 19 28 13 43 41
 18 24 46 29 41 35  9 28 32  8 38 42 33  9 16 36 10 47 27 28 47 13 24 49
 27 42 31 40]


In [143]:
print (rand_array[ [0,0,0] ] )
print( rand_array[ [0,21,-1, -2] ] )

[49 49 49]
[49 18 40 31]


# Pandas

In [144]:
!pip install pandas


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [145]:
import pandas as pd

df = pd.DataFrame(
    [ ['Jan',58,42,74,22,2.05],
    ['Feb',61,45,78,26,3.02],
    ['Mar',65,48,84,25,2.34],
    ['Apr',67,50,92,28,1.02],
    ['May',71,53,98,35,0.48],
    ['Jun',75,56,107,41,0.11],
    ['Jul',77,58,105,44,0.0],
    ['Aug',77,59,102,43,0.03],
    ['Sep',77,57,103,40,0.17],
    ['Oct',73,54,96,34,0.81],
    ['Nov',64,48,84,30,1.7],
    ['Dec',58,None,None,21,2.56],
    ['Dec',58,42,73,21,2.56] ],
    columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

In [149]:
df

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [150]:
df.info() # object - means string in Pandas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   month              13 non-null     object 
 1   avg_high           13 non-null     int64  
 2   avg_low            12 non-null     float64
 3   record_high        12 non-null     float64
 4   record_low         13 non-null     int64  
 5   avg_precipitation  13 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 752.0+ bytes


In [151]:
df.describe()

avg_high    avg_low  record_high  record_low  avg_precipitation
count  13.000000  12.000000    12.000000   13.000000          13.000000
mean   67.769231  51.000000    91.333333   31.538462           1.296154
std     7.639305   6.060303    12.323911    8.501131           1.115210
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    61.000000  47.250000    82.500000   25.000000           0.170000
50%    67.000000  51.500000    94.000000   30.000000           1.020000
75%    75.000000  56.250000   102.250000   40.000000           2.340000
max    77.000000  59.000000   107.000000   44.000000           3.020000

In [152]:
df.head()

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34
3   Apr        67     50.0         92.0          28               1.02
4   May        71     53.0         98.0          35               0.48

In [153]:
df.head(3)

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34

In [154]:
df.tail()

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [156]:
list( df.columns )

['month',
 'avg_high',
 'avg_low',
 'record_high',
 'record_low',
 'avg_precipitation']

In [157]:
df.sort_values( 'avg_high' )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56
1    Feb        61     45.0         78.0          26               3.02
10   Nov        64     48.0         84.0          30               1.70
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
9    Oct        73     54.0         96.0          34               0.81
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17

In [158]:
df.sort_values( 'avg_high', ascending=False )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [159]:
df.sort_values( ['avg_high', 'avg_low'], ascending=False )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
7    Aug        77     59.0        102.0          43               0.03
6    Jul        77     58.0        105.0          44               0.00
8    Sep        77     57.0        103.0          40               0.17
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [160]:
df.sort_values( ['avg_high', 'avg_low'], ascending=[False, True] )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [163]:
df_2 = df.sort_values( ['avg_high', 'avg_low'], ascending=[False, True] )
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [166]:
print (df_2[ 'record_low' ] )
print (type(df_2[ 'record_low' ]) )

8     40
6     44
7     43
5     41
9     34
4     35
3     28
2     25
10    30
1     26
0     22
12    21
11    21
Name: record_low, dtype: int64
<class 'pandas.core.series.Series'>


In [168]:
print (df_2[ ['record_low', 'record_high' ] ] )
print( type( df_2[ ['record_low', 'record_high' ] ] ))

    record_low  record_high
8           40        103.0
6           44        105.0
7           43        102.0
5           41        107.0
9           34         96.0
4           35         98.0
3           28         92.0
2           25         84.0
10          30         84.0
1           26         78.0
0           22         74.0
12          21         73.0
11          21          NaN
<class 'pandas.core.frame.DataFrame'>


In [169]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [170]:
df_2[ 'najas_stulpelis' ] = 5
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    najas_stulpelis  
8                 5  
6                 5  
7                 5  
5                 5  
9                 5  
4                 5  
3                 5  
2                 5  
10                5  
1                 5  
0                 5  
12                5  
11                5

In [171]:
df_2[ 'najas_stulpelis_2' ] = (df_2[ 'record_high' ] - df_2[ 'record_low' ] ) / 2
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    najas_stulpelis  najas_stulpelis_2  
8                 5               31.5  
6                 5               30.5  
7                 5               29.5  
5                 5               33.0  
9                 5               31.0  
4                 5               31.5  
3                 5               32.0  
2                 5               29.5  
10                5               27.0  
1                 5               26.0  
0                 5               26.0  
12                5               26.0  
11                5                NaN

## loc[index]

In [172]:
df_2.loc[ 10 ]

month                 Nov
avg_high               64
avg_low              48.0
record_high          84.0
record_low             30
avg_precipitation     1.7
najas_stulpelis         5
najas_stulpelis_2    27.0
Name: 10, dtype: object

In [173]:
df_2.loc[ 8 ]

month                  Sep
avg_high                77
avg_low               57.0
record_high          103.0
record_low              40
avg_precipitation     0.17
najas_stulpelis          5
najas_stulpelis_2     31.5
Name: 8, dtype: object

## iloc[ row number ]

In [175]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    najas_stulpelis  najas_stulpelis_2  
8                 5               31.5  
6                 5               30.5  
7                 5               29.5  
5                 5               33.0  
9                 5               31.0  
4                 5               31.5  
3                 5               32.0  
2                 5               29.5  
10                5               27.0  
1                 5               26.0  
0                 5               26.0  
12                5               26.0  
11                5                NaN

In [174]:
df_2.iloc[ 10 ]

month                 Jan
avg_high               58
avg_low              42.0
record_high          74.0
record_low             22
avg_precipitation    2.05
najas_stulpelis         5
najas_stulpelis_2    26.0
Name: 0, dtype: object

In [176]:
df_2.iloc[ 0 ]

month                  Sep
avg_high                77
avg_low               57.0
record_high          103.0
record_low              40
avg_precipitation     0.17
najas_stulpelis          5
najas_stulpelis_2     31.5
Name: 8, dtype: object

In [178]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    najas_stulpelis  najas_stulpelis_2  
8                 5               31.5  
6                 5               30.5  
7                 5               29.5  
5                 5               33.0  
9                 5               31.0  
4                 5               31.5  
3                 5               32.0  
2                 5               29.5  
10                5               27.0  
1                 5               26.0  
0                 5               26.0  
12                5               26.0  
11                5                NaN

In [177]:
df_2.loc[ 5:10 ] # slicing

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   

    najas_stulpelis  najas_stulpelis_2  
5                 5               33.0  
9                 5               31.0  
4                 5               31.5  
3                 5               32.0  
2                 5               29.5  
10                5               27.0

In [179]:
df_2.loc[ [5,6,7,8,9,10] ]

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
5    Jun        75     56.0        107.0          41               0.11   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
8    Sep        77     57.0        103.0          40               0.17   
9    Oct        73     54.0         96.0          34               0.81   
10   Nov        64     48.0         84.0          30               1.70   

    najas_stulpelis  najas_stulpelis_2  
5                 5               33.0  
6                 5               30.5  
7                 5               29.5  
8                 5               31.5  
9                 5               31.0  
10                5               27.0

In [180]:
df_2.loc[ [5,6,7,8,9,10] , 'avg_high' ]

5     75
6     77
7     77
8     77
9     73
10    64
Name: avg_high, dtype: int64

In [181]:
df_2.loc[ [5,6,7,8,9,10] , ['avg_high', 'record_high' ] ] # df.loc[ row idexes, column indexes ]

avg_high  record_high
5         75        107.0
6         77        105.0
7         77        102.0
8         77        103.0
9         73         96.0
10        64         84.0

In [182]:
df_2.loc[ : , ['avg_high', 'record_high' ] ]

avg_high  record_high
8         77        103.0
6         77        105.0
7         77        102.0
5         75        107.0
9         73         96.0
4         71         98.0
3         67         92.0
2         65         84.0
10        64         84.0
1         61         78.0
0         58         74.0
12        58         73.0
11        58          NaN

## changing row indexes

In [183]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    najas_stulpelis  najas_stulpelis_2  
8                 5               31.5  
6                 5               30.5  
7                 5               29.5  
5                 5               33.0  
9                 5               31.0  
4                 5               31.5  
3                 5               32.0  
2                 5               29.5  
10                5               27.0  
1                 5               26.0  
0                 5               26.0  
12                5               26.0  
11                5                NaN

In [184]:
df_3 = df_2.set_index('month')
df_3

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Jul          77     58.0        105.0          44               0.00   
Aug          77     59.0        102.0          43               0.03   
Jun          75     56.0        107.0          41               0.11   
Oct          73     54.0         96.0          34               0.81   
May          71     53.0         98.0          35               0.48   
Apr          67     50.0         92.0          28               1.02   
Mar          65     48.0         84.0          25               2.34   
Nov          64     48.0         84.0          30               1.70   
Feb          61     45.0         78.0          26               3.02   
Jan          58     42.0         74.0          22               2.05   
Dec          58     42.0         73.0          21               2.56   
Dec          58      NaN          NaN          21               2.56   

       najas_stulpelis  najas_stulpelis_2  
month                                      
Sep                  5               31.5  
Jul                  5               30.5  
Aug                  5               29.5  
Jun                  5               33.0  
Oct                  5               31.0  
May                  5               31.5  
Apr                  5               32.0  
Mar                  5               29.5  
Nov                  5               27.0  
Feb                  5               26.0  
Jan                  5               26.0  
Dec                  5               26.0  
Dec                  5                NaN

In [185]:
df_3.loc[ 'Sep' ]

avg_high              77.00
avg_low               57.00
record_high          103.00
record_low            40.00
avg_precipitation      0.17
najas_stulpelis        5.00
najas_stulpelis_2     31.50
Name: Sep, dtype: float64

In [186]:
df_3.loc[ ['Sep', 'Dec'] ]

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Dec          58     42.0         73.0          21               2.56   
Dec          58      NaN          NaN          21               2.56   

       najas_stulpelis  najas_stulpelis_2  
month                                      
Sep                  5               31.5  
Dec                  5               26.0  
Dec                  5                NaN

In [188]:
# df_3.iloc[ 'Sep' ] # neveiks
df_3.iloc[ 0 ]

avg_high              77.00
avg_low               57.00
record_high          103.00
record_low            40.00
avg_precipitation      0.17
najas_stulpelis        5.00
najas_stulpelis_2     31.50
Name: Sep, dtype: float64

In [191]:
df_3 = df_3.dropna()
df_3

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Jul          77     58.0        105.0          44               0.00   
Aug          77     59.0        102.0          43               0.03   
Jun          75     56.0        107.0          41               0.11   
Oct          73     54.0         96.0          34               0.81   
May          71     53.0         98.0          35               0.48   
Apr          67     50.0         92.0          28               1.02   
Mar          65     48.0         84.0          25               2.34   
Nov          64     48.0         84.0          30               1.70   
Feb          61     45.0         78.0          26               3.02   
Jan          58     42.0         74.0          22               2.05   
Dec          58     42.0         73.0          21               2.56   

       najas_stulpelis  najas_stulpelis_2  
month                                      
Sep                  5               31.5  
Jul                  5               30.5  
Aug                  5               29.5  
Jun                  5               33.0  
Oct                  5               31.0  
May                  5               31.5  
Apr                  5               32.0  
Mar                  5               29.5  
Nov                  5               27.0  
Feb                  5               26.0  
Jan                  5               26.0  
Dec                  5               26.0

In [192]:
df_3.to_csv('weather.csv')